-- Preserva o histórico: desativa os presentes antigos em vez de apagar (há vínculos em gift_claims)
update public.gifts set active = false where active = true;

-- Nova lista divertida: valores ficam como "valor livre" para os noivos definirem depois
insert into public.gifts (name, description, category, value_label, value_cents, sort_order, active) values
('🍔 1 ano de Fast Food para o casal','Porque depois do casamento ninguém quer cozinhar todos os dias, né? 😂','comida','Valor livre',null,1,true),
('🍕 Vale Pizza','Para aqueles dias em que cozinhar está completamente fora de cogitação.','comida','Valor livre',null,2,true),
('🍫 Estoque de chocolate da noiva','Uma pequena contribuição para manter a paz dentro de casa. ❤️😂','comida','Valor livre',null,3,true),
('☕ Café para o casal','Para manter os recém-casados funcionando depois de noites mal dormidas. 😂','comida','Valor livre',null,4,true),
('🥩 Churrasco do casal','Porque felicidade de recém-casado também combina com churrasco.','comida','Valor livre',null,5,true),
('🍿 Maratona de filmes e séries','Para o casal passar o domingo debaixo da coberta discutindo qual filme assistir. 😂❤️','diversao','Valor livre',null,6,true),
('🎮 Noite de videogame do noivo','Porque todo casamento precisa de equilíbrio... inclusive entre romance e videogame. 😂','diversao','Valor livre',null,7,true),
('📸 Curso para o noivo aprender a tirar foto','Para ele finalmente aprender a tirar uma foto boa da noiva sem cortar a cabeça dela. 😂📸','diversao','Valor livre',null,8,true),
('🧖‍♀️ Dia de Spa para a noiva','Depois de organizar casamento, ela merece! 💅❤️','diversao','Valor livre',null,9,true),
('🎬 Cinema + pipoca gigante','Para o casal brigar pelo braço da poltrona como gente grande. 😂','diversao','Valor livre',null,10,true),
('🧹 Um mês sem discutir quem vai lavar a louça','Um presente raro e praticamente impossível de encontrar no mercado. 😂','casal','Valor livre',null,11,true),
('🧺 Vale lavanderia','Para ganhar alguns dias de liberdade das roupas acumuladas.','casal','Valor livre',null,12,true),
('🛠️ Curso de montagem de móveis para o noivo','Para provar que ele consegue montar alguma coisa sem olhar o manual... ou quase. 😂','casal','Valor livre',null,13,true),
('😴 Domingo sem fazer nada','Um presente luxuoso: acordar tarde, ficar de pijama e não ter absolutamente nenhuma obrigação.','casal','Valor livre',null,14,true),
('😂 Terapia de casal preventiva','Porque queremos começar a vida de casados preparados para tudo. 😂','casal','Valor livre',null,15,true),
('🧹 Faxina dos sonhos','Para a casa brilhar sem nenhum dos dois precisar levantar um dedo. ✨','casal','Valor livre',null,16,true),
('🍳 Café da manhã na cama','O clássico romântico que todo recém-casado merece viver pelo menos uma vez. 🥰','romance','Valor livre',null,17,true),
('🥂 Jantar romântico','Uma ajudinha para manter o romance vivo depois de começar a vida de casados. ❤️','romance','Valor livre',null,18,true),
('🌹 Surpresa romântica do mês','Flores, bilhete e aquele sorriso bobo garantido. 🥰','romance','Valor livre',null,19,true),
('💃 Aula de dança para o casal','Para nunca mais passarem vergonha na pista dos casamentos dos amigos. 😂','romance','Valor livre',null,20,true),
('🧳 Fundo para a próxima viagem','Uma ajudinha para o casal continuar colecionando histórias pelo mundo. ✈️❤️','viagem','Valor livre',null,21,true),
('✈️ Upgrade na lua de mel','Aquele empurrãozinho para transformar uma viagem boa em inesquecível.','viagem','Valor livre',null,22,true),
('🍹 Drink de frente para o mar','Porque brindar o casamento com água não tem a mesma graça. 😂','viagem','Valor livre',null,23,true),
('🏨 Uma noite a mais no hotel','Para a lua de mel durar mais 24 horas de pura felicidade. ❤️','viagem','Valor livre',null,24,true),
('🏠 Fundo para a casinha dos recém-casados','Para ajudar a transformar a nossa casa em nosso cantinho favorito. ❤️','casa','Valor livre',null,25,true),
('🛋️ Canto da preguiça','Uma contribuição para o sofá onde vamos passar 90% da vida de casados. 😂','casa','Valor livre',null,26,true),
('🕯️ Kit casa cheirosa','Velas e aromas para a casa ter cheiro de lar desde o primeiro dia.','casa','Valor livre',null,27,true),
('🖼️ Quadro com a foto do casamento','Para pendurar na parede e lembrar todos os dias desse momento. ❤️','casa','Valor livre',null,28,true),
('💸 Fundo "a vida de casado não é barata"','Porque aparentemente amor não paga boleto. 😂','fundo','Valor livre',null,29,true),
('💰 Cota do cofrinho do casal','Cada real vira um sonho a mais na nossa lista. 🐷✨','fundo','Valor livre',null,30,true),
('🆘 Fundo emergência "queimou o jantar"','Para os dias em que a tentativa de cozinhar termina em delivery. 😂','fundo','Valor livre',null,31,true),
('🎁 Cota surpresa','Você escolhe o valor, a gente escolhe como agradecer. ❤️','fundo','Valor livre',null,32,true),
('📱 Vale streaming por 1 ano','Para as maratonas de série nunca acabarem. 🍿','diversao','Valor livre',null,33,true),
('🍦 Vale sorvete do fim de semana','Porque toda briga de casal termina mais rápido com sorvete. 😂','comida','Valor livre',null,34,true),
('🥞 Brunch de domingo','Para começar o domingo como se fosse feriado. 🥰','comida','Valor livre',null,35,true),
('🧘‍♂️ Aula de paciência para o noivo','Item em fase de testes. Resultados não garantidos. 😂','casal','Valor livre',null,36,true);